use_frameworks!

platform :ios, '9.0'

target 'ADAlertController-swift_Example' do
  pod 'ADAlertController-swift', :path => '../'

  target 'ADAlertController-swift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
