excluded:
    - Pods
    - Source/ExcludedFolder
    - Source/ExcludedFile.swift
    
disabled_rules:
    - line_length
    - type_name
    - trailing_whitespace
    - trailing_newline
    - vertical_whitespace
    - implicit_getter
    - type_body_length
    - function_body_length
    - file_length
    - no_fallthrough_only

force_cast: warning
# 隐式


